# ==============================================================
# = PriceArt Web Service con Autenticazione JWT
# ==============================================================
server:
  port: 507${seq}
 
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
spring:
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# ==============================================================
# = ZipKin parameters
# ==============================================================
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
      #type: rabbit 
# ==============================================================
# = Sleuth parameters
# ==============================================================
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
    
  
# ==============================================================
# = Proprietà RabbitMQ
# ==============================================================      
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq


# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh,hystrix.stream
                
        