# ==============================================================
# = Promo Web Service con Autenticazione JWT
# ==============================================================

server:
  #port: 8091
  port: 809${seq}

spring:
  application:
    name: PromoWebService
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
# ==============================================================
# = ZipKin parameters
# ==============================================================
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
      #type: rabbit  
# ==============================================================
# = Sleuth parameters
# ==============================================================
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
    
# ==============================================================
# = Feign Parameters
# ============================================================== 
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    connection-timeout: 3000
  client:
    config:
      default:
        connectTimeout: 300000 #5 MINUTI
        readTimeout: 300000
        
# ==============================================================
# = Eureka Properties  
# = Nota: prima di attivare il servizio servono tre heartbeat
# ==============================================================
eureka:
# ==============================================================
# = Impostazioni Instance
# ============================================================== 
  instance:
    #intervallo di attesa prima della rimozione del servizio (def 90 sec)
    lease-expiration-duration-in-seconds: 60
    #intervallo di invio dell'heartbeat (def 30 sec)
    leaseRenewalIntervalInSeconds: 15
    #id di identificazione dell'istanza
    instanceId: ${server.port}-${spring.application.name}-${seq}
    #registrazione per indirizzo ip (defualt hostname)
    preferIpAddress: true
# ==============================================================
# = Impostazioni Client
# ============================================================== 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: ${EUREKA_URL:http://user:BimBumBam_2018@localhost:8761/eureka/}
    #time out di connessione in secondi al server Eureka (def 5 sec) 
    eureka-server-connect-timeout-seconds: 8 
    
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hystrix.stream
   
    
# ==============================================================
# = Configurazione levello di Log PriceClient
# ==============================================================      
logging:
  level:
    com.xantrix.webapp.controller: DEBUG
    org.springframework.cloud: ERROR
            
            
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================          
gestuser:
  password: BimBumBam_2018
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella
  

